# Site settings
title: Jon Chan
email: me@jonhmchan.com
description: > # this means to ignore newlines until "baseurl:"
  I think a lot about code, food, and philosophy.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://jonchan.io/" # the base hostname & protocol for your site
twitter_username: jonhmchan
github_username:  jonhmchan

# Build settings
markdown: kramdown
